import React from 'react';
import { LandingHeader } from '@/components/DashboardHeader';
import PageFooter from '@/components/PageFooter';

interface PrivacyPolicyPageProps {
    onNavigate: (step: string) => void;
    userProfile: any;
}

export function PrivacyPolicyPage({ onNavigate, userProfile }: PrivacyPolicyPageProps) {
    return (
        <div className="min-h-screen flex flex-col bg-[#f5f5f5]">
            <LandingHeader onNavigate={onNavigate} onLogout={() => onNavigate('login')} userProfile={userProfile} />

            <div className="flex-1 p-4 md:p-8 flex justify-center pb-20">
                <div className="bg-white border border-gray-300 shadow-sm w-full max-w-4xl">
                    <div className="bg-[#6c757d] text-white px-4 py-3 border-b border-gray-300">
                        <h2 className="text-sm md:text-[15px] font-bold uppercase tracking-wide">
                            Privacy Policy & Legal Disclaimer
                        </h2>
                    </div>

                    <div className="p-6 md:p-10 space-y-6 text-[13px] text-gray-800 leading-relaxed font-sans">
                        
                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">1. Educational & Simulation Purposes Only</h3>
                            <p>
                                This platform ("KCET Simulator") is built strictly for <strong>educational and demonstrative purposes</strong>. It is designed to help students understand the complex option entry and seat allotment processes before the actual counseling takes place. The mock allotments generated by this simulator are <strong>not real</strong> and do not guarantee you a seat in any institution.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">2. No Affiliation with KEA</h3>
                            <p>
                                This website is an independent community-driven project and is <strong>NOT affiliated, associated, authorized, endorsed by, or in any way officially connected with the Karnataka Examinations Authority (KEA)</strong>, the Government of Karnataka, or any other official educational body. For official information, always visit the official KEA website.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">3. Privacy & Data Storage</h3>
                            <p>
                                We deeply respect your privacy. <strong>We do not collect, transmit, share, or store any of your personal data on external servers.</strong> 
                            </p>
                            <ul className="list-disc pl-5 mt-2 space-y-1">
                                <li>All the information you input (including CET Numbers, Names, Ranks, Categories, and Option Entries) is stored <strong>100% locally in your device's browser storage (Local Storage)</strong>.</li>
                                <li>If you clear your browser data or use a different device, your simulator progress will be completely lost.</li>
                                <li>We use no third-party tracking cookies or analytics that monitor your identifiable data.</li>
                            </ul>
                        </section>

                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">4. Accuracy of Cutoffs & Algorithm</h3>
                            <p>
                                All mock allotments provided on this platform are simulated based on the official <strong>KCET 2025 Round 1, Round 2, and Round 3 cutoff data</strong>. While we have done our best to replicate the allotment logic, our algorithm is an approximation and may not perfectly reflect KEA's proprietary sorting algorithms, specific category reservations, or real-time seat matrix updates. 
                            </p>
                        </section>

                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">5. Legal Disclaimer & Liability Limitation</h3>
                            <p>
                                By using this simulator, you acknowledge and agree that no legal actions can be taken against the developers and creators of this project. The creators shall not be held liable for any direct, indirect, incidental, or consequential damages, misunderstandings, loss of admission opportunities, or any other consequences arising from the use of this simulator. You are solely responsible for verifying your options and participating accurately in the official KEA portal when the time comes.
                            </p>
                        </section>

                        <section>
                            <h3 className="text-[15px] font-bold mb-2 text-black">6. Credits</h3>
                            <p>This project was brought to life by the community, for the community.</p>
                            <div className="flex flex-col gap-2 mt-2">
                                <div className="flex items-center gap-2">
                                    <svg className="w-5 h-5 text-[#5865F2]" viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z" />
                                    </svg>
                                    <span className="font-bold">flux_ai (aka Yashwin)</span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <svg className="w-5 h-5 text-[#5865F2]" viewBox="0 0 24 24" fill="currentColor">
                                        <path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z" />
                                    </svg>
                                    <span className="font-bold">Azalea</span>
                                </div>
                            </div>
                        </section>

                        <div className="pt-6 pb-2 text-center">
                            <button
                                onClick={() => onNavigate('landing')}
                                className="bg-[#000080] hover:bg-blue-900 text-white font-bold py-2 px-8 rounded shadow text-[14px]"
                            >
                                Back to Dashboard
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <PageFooter />
        </div>
    );
}
