import React from 'react';
import { LandingHeader } from '@/components/DashboardHeader';
import PageFooter from '@/components/PageFooter';
import CreditsPrivacyCard from '@/components/CreditsPrivacyCard';

interface PrivacyPolicyPageProps {
    onNavigate: (step: string) => void;
    userProfile: any;
}

export function PrivacyPolicyPage({ onNavigate, userProfile }: PrivacyPolicyPageProps) {
    return (
        <div className="min-h-screen flex flex-col bg-[#F8FAFC]">
            <LandingHeader onNavigate={onNavigate} onLogout={() => onNavigate('login')} userProfile={userProfile} step="privacy" />

            <div className="flex-1 p-4 md:p-8 flex flex-col items-center gap-6 max-w-4xl mx-auto w-full pb-20 select-none">
                
                {/* Full Detailed Privacy Policy Card */}
                <div className="bg-white rounded-2xl shadow-lg border border-slate-200 w-full overflow-hidden">
                    <div className="bg-[#1B365D] text-white p-5 border-b-4 border-[#D99A29] flex items-center justify-between">
                        <h1 className="text-base md:text-lg font-bold tracking-tight">Privacy Policy &amp; Legal Disclaimer</h1>
                        <span className="text-[11px] bg-[#24426A] text-[#D99A29] px-3 py-1 rounded-full font-semibold border border-[#305380]">
                            Version 1.5.18
                        </span>
                    </div>

                    <div className="p-6 md:p-8 space-y-6 text-slate-700 text-xs md:text-sm leading-relaxed">
                        <div className="bg-amber-50 border-l-4 border-[#D99A29] p-4 rounded-r-xl text-amber-900 text-xs font-medium">
                            📌 <strong>Important Notice:</strong> This simulator is developed independently for student guidance and educational preparation. It is <strong>NOT</strong> affiliated with the Karnataka Examinations Authority (KEA).
                        </div>

                        <div className="space-y-4">
                            <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50">
                                <h3 className="font-bold text-[#1B365D] text-sm md:text-base mb-1">1. Educational &amp; Simulation Purposes Only</h3>
                                <p className="text-slate-600">
                                    This platform ("KCET Simulator") is built strictly for educational and demonstrative purposes. The mock allotments generated by this simulator are algorithmically derived from past cutoff data and do not guarantee seats in real counseling.
                                </p>
                            </div>

                            <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50">
                                <h3 className="font-bold text-[#1B365D] text-sm md:text-base mb-1">2. No Affiliation with KEA</h3>
                                <p className="text-slate-600">
                                    This website is an independent open project. It is <strong>NOT</strong> affiliated with, authorized, maintained, sponsored, or endorsed by the Karnataka Examinations Authority (KEA) or any government entity.
                                </p>
                            </div>

                            <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50">
                                <h3 className="font-bold text-[#1B365D] text-sm md:text-base mb-1">3. Privacy &amp; Local Data Storage</h3>
                                <p className="text-slate-600">
                                    We respect your privacy completely. <strong>No personal data is uploaded to external servers.</strong> All information entered (such as your mock choices or ranks) is stored locally within your browser's Local Storage cache and can be cleared at any time.
                                </p>
                            </div>

                            <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50">
                                <h3 className="font-bold text-[#1B365D] text-sm md:text-base mb-1">4. Disclaimer &amp; Limitation of Liability</h3>
                                <p className="text-slate-600">
                                    By using this simulator, you agree that the creators and contributors shall not be held liable for any decisions made based on the simulated allotment predictions. Always refer to official KEA portals for official announcements.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Credits Card */}
                <CreditsPrivacyCard onNavigate={onNavigate} />

                {/* Back to Dashboard Button */}
                <div className="pt-2 text-center">
                    <button
                        onClick={() => onNavigate('landing')}
                        className="bg-[#1B365D] hover:bg-[#122744] text-white font-bold py-2.5 px-8 rounded-xl shadow-md transition-all text-xs md:text-sm cursor-pointer"
                    >
                        ← Back to Dashboard
                    </button>
                </div>
            </div>

            <PageFooter onNavigate={onNavigate} />
        </div>
    );
}
